# Generated by Django 4.2.16 on 2024-09-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.PositiveBigIntegerField(help_text='Time in minutes')),
                ('ingredients', models.TextField(help_text='List ingredients and separate with commas')),
            ],
        ),
    ]
